### ISSUE TITLE
Some strings can't be decrypted

### ISSUE THREAD

**Issue by nanisise** [Sinflower/TES-Patcher#1]
Hi, I use the tool to decrypt "Dark Elf", this game is encrypted by TES for sure, but there are some strings which can't be decrypted.
Img (in the red frame):
https://imgur.com/a/fHh6gcO

I try the parameter -D to dump all content in main.rvdata2, but still can't find the string in above image.
Is there something I've got wrong? Do you have any ideas?
Thanks.

**Comment by Sinflower** [comment]
Hi,

strings like armor, weapon or certain character information are generally stored in the default RPGMaker files e.g. armor.rvdata2, weapons.rvdata2 etc. to modify them you will either need a copy of RPGMaker VX Ace or [RPGMaker Trans](https://rpgmakertrans.bitbucket.io/).

**Comment by nanisise** [comment]
Thanks for your reply.
In fact, I've extracted all resources and used the RPG Maker VX ACE read them. The database of armor and weapons are all Japanese, so the developer use some way I don't know to cover original string. My guess it may be in  main.rvdata2
By the way, I also dump all script and try find the string, nothing found.
Could you check this? 
Tkanks.

**Comment by nanisise** [comment]
the script in the game like this:
#// 防具名前
  ARMOR_NAME = {}
  ARMOR_NAME[1]  = "Bikini Aromors"
  ARMOR_NAME[2]  = "/--Defensive Decoration--/"
  ARMOR_NAME[3]  = "Mercenary Guardian"
  ARMOR_NAME[4]  = "Amulet"
  ARMOR_NAME[5]  = "Knight Guardian"
  ARMOR_NAME[6]  = "Soldier Guard"
  ARMOR_NAME[7]  = "External Protection"
  ARMOR_NAME[8]  = "Blast Guard"
..........
  ARMOR_NOTE = {}
  ARMOR_NOTE[1]  = ""
  ARMOR_NOTE[2]  = ""
  ARMOR_NOTE[3]  = "Amulet the common soldiers like to use \n[Types]\\ATYPE [defense]+\\DEF"
  ARMOR_NOTE[4]  = "Unbelievable amulet with defense magic \n[Types]\\ATYPE [defense]+\\DEF"
  ARMOR_NOTE[5]  = "Amulet knight like to use \n[Types]\\ATYPE [defense]+\\DEF"
........

The first armor note, which is the string I mentioned, is empty in script, I try to fill another string, nothing change, so it's very weird.

**Comment by Sinflower** [comment]
It looks like the notes for all but the base armor are changed in the translation file, the base armor note is in the armor database [bottom right](https://i.imgur.com/est0lGu.png).

**Comment by nanisise** [comment]
Thanks for your reply again.

I didn't notice the bottom right comment, my bad. I will try to mod this and see if it will changes.
Thanks.
