### ISSUE TITLE
Error when decrypted with -a

### ISSUE THREAD

**Issue by ghost** [Sinflower/TES-Patcher#2]
Hello, I'm recently trying to translate a game made with RPG Maker VX Ace personally, and since the game seemed to be encrypted with TES, I used TES Patcher to decrypt main.rvdata2 file.

Since choices are too encrypted with TES, I used command 'TES_Patcher -e -a 102' (102 is the Event Code for Show Choices) to extract, and then translated extracted scripts.

The problem happened when I patched main.rvdata2. Whenever I test-run the game, and get to the point where the choice comes out, the game just returns error 《Script 'Game_Interpreter' line 285: NoMethodError occured. undefined method ‘each' for "what I've translated":String》. I guessed I might have messed with the script by accident, so I tested by getting a fresh main.rvdata2, don't edited, decrypt it with the same command and then patch the file without editing anything. But the game still returns error 《Script 'Game_Interpreter' line 285: NoMethodError occured. undefined method 'each' for #<String:0x13d7c374>》.

I'm not really sure what's wrong. Could you help me out with this? Thanks.

**Comment by Sinflower** [comment]
Hi,
choices should be extracted by default so you don't need the -a 102 parameter.
The error you get is actually the result of a bug in the patcher.

**Comment by ghost** [comment]
Um, if that's a bug in the patcher, does that mean there's nothing much I can do for now...?

**Comment by Sinflower** [comment]
As I mentioned before, choices are extracted by default. Extract the main without any additional -a parameters and search for:
EVENT CODE: 408

**Comment by ghost** [comment]
Huh, strange. I've extracted without any additional parameters, but there's no EVENT CODE: 408 present.... Just for comparison, here's an image comparing script for default extraction and -a 102 added extraction.
https://imgur.com/a/svTmOPz
The highlighted part is the choice text, extracted from  -a 102.

When I printed out the list of used events in game using -c, there was no 408 there. Here's the list of events in game.
https://imgur.com/a/Pz6CdwW

Could it be that the game creator didn't use ordinary way of presenting choices?

**Comment by Sinflower** [comment]
This is indeed strange. Could you tell me the game? I will then take a look and fix the patcher.

**Comment by ghost** [comment]
It's R-18 RPG Maker VX Ace game, called 'ビッチポリス ―BITCH POLICE―'.

**Comment by Sinflower** [comment]
I think I fixed the bug, at least it worked for the first choice. Your usage of -a 102 was indeed required to extract the choices. I think, that might be because the game is (compared to the other games using TES) rather old and might be using an older version of the TES plugin.

I would recommend you to rerun the extraction (you will need to move or delete the old extraction folder beforehand because the patcher does not override existing files) to make sure you get a clean work base.

**Comment by ghost** [comment]
I've tried the new build, but I think this build is not patching main.rvdata2 properly. Whatever edits I make to scripts aren't applied to the game.

**Comment by Sinflower** [comment]
There was indeed a bug in the build that prevented patching ... I should really stop adding "features" before posting. Below the new (hopefully working) version.

[TES_Patcher.zip](https://github.com/Sinflower/TES-Patcher/files/2783525/TES_Patcher.zip)
[TES_Patcher_src.zip](https://github.com/Sinflower/TES-Patcher/files/2783526/TES_Patcher_src.zip)

**Comment by ghost** [comment]
Tested, and this version works perfectly. Thanks a lot!
