### ISSUE TITLE
0.2.2 version error

### ISSUE THREAD

**Issue by Magnus111111** [Sinflower/TES-Patcher#3]
This error occurs when running 0.2.2v.

FATAL ERROR: Fail to create process

This error does not occur in 0.2.1.

**Comment by Sinflower** [comment]
Please test if this version works
[TES_Patcher.zip](https://github.com/Sinflower/TES-Patcher/files/3124907/TES_Patcher.zip)

**Comment by Magnus111111** [comment]
same error

**Comment by Sinflower** [comment]
Try this one
[TES_Patcher.zip](https://github.com/Sinflower/TES-Patcher/files/3126406/TES_Patcher.zip)

If this version also does not work, please post your OS as well as the game you are trying to patch.

**Comment by Magnus111111** [comment]
error solved.
Thank you very much for your efforts.
