### ISSUE TITLE
I cant open TES_Patcher

### ISSUE THREAD

**Issue by dot-super** [Sinflower/TES-Patcher#4]
cmd info:
<internal:gem_prelude>:4:in `require': No such file or directory -- C:/Users/澶╅粦鍒扮珯/AppData/Local/Temp/ocrA61A.tmp/lib/ruby/2.4.0/rubygems.rb (LoadError)
        from <internal:gem_prelude>:4:in `<internal:gem_prelude>'

what should I do?

**Comment by dot-super** [comment]
I solved this problem, and when I used it, the game files were all deleted

**Comment by Sinflower** [comment]
How did you solve the problem?
Which game did you try to patch?

**Comment by dot-super** [comment]
the game is [ONEONE1] 軋轢のイデオローグAppend, and I changed User variables about Temp. It cannot recognize Chinese path.

**Comment by Sinflower** [comment]
My best guess is, that when you changed the temp variable you set it to the game folder, causing the ocra cleanup to delete the entire folder, as it deletes the temp data after the execution.
The quickest solution I can think of right now is,
either you directly use the ruby code from the git or
you set the temp path to a custom folder within your game data folder, e.g., create a new temp folder and us that.

**Comment by dot-super** [comment]
Yeah. It will not store temp files according to which folder I set, but use the current folder.
In version 0.2.2, CMD info display
 FATAL ERROR: Failed to get temp file name.

And in version 0.2.3,TES Patcher requires administrator to run，CMD will flash by, and I can’t get any information.

btw, only v0.2.2 will delete files. v0.2.3 no response no result.

**Comment by dot-super** [comment]
Finally, I caught the error message. It's work. Thanks for your help.
