### ISSUE TITLE
Update please for new windows version

### ISSUE THREAD

**Issue by sh1mmer1ng** [Sinflower/TES-Patcher#5]
The patcher does not open on version 21H1
Can you update please?

**Comment by Sinflower** [comment]
Strange, works fine for me on 21H2.
You might need to run your shell as admin or it tends to open in a different Window.

**Comment by sh1mmer1ng** [comment]
I have a problem with compatibility. The program immediately closes after launch, maybe I don't have some toolkits installed?

**Comment by Sinflower** [comment]
The compatibility message is just some windows non-sense, you can ignore it.
As I have mentioned before, for some reason ocra exe requires an admin shell to properly display the output.
As a general note, this is a pure console-based application, i.e., you have to run it with the parameters described in the readme.
